Models/ErrorViewModel.cs
namespace ToDoList.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/ToDoItem.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ToDoList.Models;

public class ToDoItem
{
    [Key]
    public int Id { get; set; }
    
    [Required(ErrorMessage = "الوصف مطلوب")] // حقل إلزامي
    public string Description { get; set; }

    
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;

namespace ToDoList.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ToDoListController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ToDoList.Data;
using ToDoList.Models;

namespace ToDoList.Controllers;

public class ToDoListController : Controller
{
        private readonly ApplicationDbContext _context;
        private IWebHostEnvironment _webHostEnvironment;
        public ToDoListController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment) {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            
        }
        
     public IActionResult Index(string description, string userName)
    {
        // إذا تم إدخال وصف للبحث
        if (!string.IsNullOrWhiteSpace(description))
        {
            var search = _context.items.Where(s => s.Description.Contains(description)).ToList();
            ViewData["UserName"] = userName; // تمرير اسم المستخدم إلى العرض
            return View(search);
        }

        // في حالة عدم وجود بحث، جلب كل البيانات
        var getdata = _context.items.ToList();
        ViewData["UserName"] = userName; // تمرير اسم المستخدم إلى العرض
        return View(getdata);
    }
    
        public IActionResult CreateList(ToDoItem items) {
            _context.Add(items);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


         public IActionResult DeleteItem(int id) {

            var ItemDelete = _context.items.SingleOrDefault(i=> i.Id == id);
            
            if (ItemDelete != null) {
                _context.items.Remove(ItemDelete);
                _context.SaveChanges();
            }
       
            return RedirectToAction("Index");

        }

        // [HttpPost]
        // public IActionResult EditItem(int id, [FromBody] ToDoItem updatedItem)
        // {
        //     var item = _context.items.SingleOrDefault(e => e.Id == id);
        //     if (item != null)
        //     {
        //         item.Description = updatedItem.Description; // تحديث الوصف الجديد
        //         _context.items.Update(item);
        //         _context.SaveChanges(); // حفظ التعديلات
        //     }
        //     return RedirectToAction("Index");

        // }

            public IActionResult EditItem(int id)
        {
            var item = _context.items.SingleOrDefault(e => e.Id == id);
            return View(item);

        }



        public IActionResult UpdateItem(ToDoItem items) {
            _context.items.Update(items);
            _context.SaveChanges(); // حفظ التعديلات

            return RedirectToAction("Index");


        }
        // [HttpPost]
        // public IActionResult Search(string Description) {
        //      if (Description != null) {
        //         var search = _context.items.Where(s=>s.Description.Contains(Description)).ToList();
        //         return PartialView("_partial/_IndexPartialData", search);


        //     }

        //     var item = _context.items.ToList();
        //     return PartialView("_partial/_IndexPartialData", item);


        // }

       


}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="text-center" style="min-height: 50vh; display: flex; flex-direction: column; justify-content: flex-end; align-items: center;">
    <h1 class="display-4 mb-auto mt-5">Mange Your Time with To-Do-List!</h1>

           <form asp-controller="ToDoList" asp-action="Index" method="get">
    <!-- حقل الإدخال -->
            <label class="d-flex justify-content-start text-white">Enter Your Name</label>
            <input type="text" name="userName" placeholder="Name" class="mb-3">
            <button type="submit" class="btn btn-secondary mb-5 custom-btn">Start</button>
</form>




Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoList</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoList.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='https://fonts.googleapis.com/css?family=Almarai' rel='stylesheet'>
    <link rel="stylesheet" href="~/css/list.css" asp-append-version="true" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDoList Website</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-white">
            &copy; 2025 - ToDoList - Made by Betool Aljuraish<a asp-area="" asp-controller="Home" asp-action=""></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/list.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/ToDoList/EditItem.cshtml
@model ToDoItem

@{
    
    Layout="/Views/Shared/_Layout.cshtml";
}
@* <div class="modal" tabindex="-1" id="del">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">تأكيد الحذف</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>هل بالفعل تريد حذف هذا السجل؟</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إلغاء الأمر</button>
        <button type="button" class="btn btn-danger" onclick="confirmdelete1()">حذف</button>
      </div>
    </div>
  </div>
</div> *@
@* 
<div id="container1">
  <div class="row">
    <div class="col">

      	<form class="search1" asp-action="UpdateItem" method="post">
        <h1>To-Do List <i class="fa fa-plus"></i><button type="submit" style="border: none; background: none;"></button></h1>
        <input type="hidden" asp-for="@Model.Id">

        <input type="text" asp-for="@Model.Description">
    </form>
    </div>
  </div>

    

</div> *@


<div class="container1">
    <div class="row">
        <div class="col">
            <div class="search ">
                <h1>Editing List</h1>

                <form class="search1 flex-column d-flex align-items-center" asp-action="UpdateItem" method="post">
                     <input type="hidden" asp-for="@Model.Id">
                     <input type="text" asp-for="@Model.Description">
                      <button type="submit" class="btn m-2 w-100" style="background-color:#b3c583">Edit</button>
                 </form>
              
              


        

            </div>
        </div>
    </div>

Views/ToDoList/Index.cshtml
@model IEnumerable<ToDoItem>

@{
    
    Layout="/Views/Shared/_Layout.cshtml";
    var userName = ViewData["UserName"] as string;

}
@* <div class="modal" tabindex="-1" id="del">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">تأكيد الحذف</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>هل بالفعل تريد حذف هذا السجل؟</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إلغاء الأمر</button>
        <button type="button" class="btn btn-danger" onclick="confirmdelete1()">حذف</button>
      </div>
    </div>
  </div>
</div> *@
<h1 class="display-4 mb-auto mt-5">Welcome, @userName!</h1>

<div class="container1">

    <div class="row">
        <div class="col">
            <div class="search ">
                <h1>Search - Filter</h1>

             <form class="search1 d-flex flex-column align-items-center w-100" asp-action="Index" method="get">
    <!-- حقل الإدخال -->
            <input type="text" name="Description" placeholder="Search" class="mb-3 w-100">
            
            <!-- مجموعة الأزرار -->
            <div class="d-flex justify-content-between w-100 mt-1">
                <button  type="submit" class="btn w-100 me-2" style="background-color:#b3c583">Search</button>
                <a asp-action="Index" class="btn btn-secondary w-100">Remove Filter</a> @* هذا هو التعديل! *@
            </div>
            </form>


               

            </div>
        </div>
    </div>


        <div class="col mt-2">
            <form asp-action="CreateList" method="post">
                <h1>To-Do List <i class="fa fa-plus"></i></h1>
                <input type="text" name="Description" placeholder="Add New Todo">
             </form>

        

            <ul>
                @foreach (var items in Model) {
                    <li>
                        <div id="text-@items.Id" contenteditable="false" onkeydown="handleKeyDown(event, @items.Id)" onblur="saveEditedText(@items.Id)">
                            
                            <span>
                                <a asp-action="DeleteItem" asp-route-id="@items.Id">
                                    <i class="fa fa-trash"></i>
                                </a>
                                <a asp-action="EditItem" asp-route-id="@items.Id">
                                    <i class="fa fa-pencil"></i>
                                </a>
                            </span>
                            @items.Description

                        </div>

                    @* <span><a onclick="showmessage(@items.Id)"><i class="fa fa-trash"></i></a></span>@items.Description *@

                    </li>
            
                }
            </ul>
        </div>

        
</div>


   
	